//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPLabSheetParserDLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabSheetParserRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabSheetParserRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPLabSheetParserDLL.Resources.LabSheetParserRes", typeof(LabSheetParserRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] has to be following [{1}] in the file.
        /// </summary>
        public static string _HasToBeFollowing_InTheFile {
            get {
                return ResourceManager.GetString("_HasToBeFollowing_InTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string _IsRequired {
            get {
                return ResourceManager.GetString("_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] requires [{1}] values.
        /// </summary>
        public static string _Requires_Value {
            get {
                return ResourceManager.GetString("_Requires_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Line.
        /// </summary>
        public static string EmptyLine {
            get {
                return ResourceManager.GetString("EmptyLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file at line [{0}]. {1}.
        /// </summary>
        public static string ErrorReadingFileAtLine_Error_ {
            get {
                return ResourceManager.GetString("ErrorReadingFileAtLine_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter [{0}].
        /// </summary>
        public static string UnknownParameter_ {
            get {
                return ResourceManager.GetString("UnknownParameter_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version has to be the first item in the file.
        /// </summary>
        public static string VersionHasToBeFirstItemInFile {
            get {
                return ResourceManager.GetString("VersionHasToBeFirstItemInFile", resourceCulture);
            }
        }
    }
}
